CREATE DATABASE media CHARACTER SET utf8 COLLATE utf8_general_ci;

USE media;

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  UNIQUE unique_name(name(10))
  );

INSERT INTO categories VALUES
  (DEFAULT, 'Аудио'),
  (DEFAULT, 'Видео'),
  (DEFAULT, 'Фото');

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS files;
CREATE TABLE files (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  desription TEXT,
  tags TEXT,
  user_id BIGINT UNSIGNED,
  path VARCHAR(255),
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);